@startuml
!pragma teoz true

box  #LightBlue
participant "Hotwheels Car" as Hotwheels
boundary "Arduino UNO R4" as Arduino
box  #LightGreen
queue "Feeder" as Feeder
end box
database "Pantry Cloud" as Pantry
control "UI Server" as UIServer
participant "Smart TV" as TV
end box

Hotwheels -[#red]>(20) Arduino : via Sensor
Arduino -[#red]>(20) Feeder : websocket 
Feeder -[#red]>(20) Pantry : store speed as json
UIServer -[#green]>(20) Pantry: poll for speed entry
UIServer -[#green]>(40) TV : Push speed to browser on TV

@enduml